from pathlib import Path
import re

# VoxBook 0.9.2: first baseline on the persistent Android signing identity.

p = Path('web/src/main.js')
s = p.read_text()
s = s.replace('VoxBook 0.9.1 · Deutsch & English', 'VoxBook 0.9.2 · Deutsch & English')
s = s.replace('id="updateVersion">v0.9.1', 'id="updateVersion">v0.9.2')
p.write_text(s)

j = Path('app/src/main/java/com/varoxan/voxbook/MainActivity.java')
js = j.read_text().replace('public String appVersion() { return "0.9.1"; }', 'public String appVersion() { return "0.9.2"; }')
j.write_text(js)

g = Path('app/build.gradle.kts')
gs = g.read_text()
gs = re.sub(r'versionCode = \d+', 'versionCode = 15', gs)
gs = re.sub(r'versionName = "[^"]+"', 'versionName = "0.9.2"', gs)

# Explicit signingConfig so the APK does not depend on Gradle's ephemeral
# runner-local debug keystore. The keystore itself is restored/generated by CI
# outside the public repository.
if 'create("voxStable")' not in gs:
    gs = gs.replace(
        '    defaultConfig {',
        '''    signingConfigs {\n        create("voxStable") {\n            storeFile = file(System.getProperty("user.home") + "/.voxbook-signing/voxbook.keystore")\n            storePassword = "android"\n            keyAlias = "androiddebugkey"\n            keyPassword = "android"\n        }\n    }\n\n    defaultConfig {''',
        1,
    )
    gs = gs.replace(
        '    buildTypes {\n',
        '''    buildTypes {\n        getByName("debug") {\n            signingConfig = signingConfigs.getByName("voxStable")\n        }\n''',
        1,
    )
g.write_text(gs)
