import './style.css';
import { PocketTTS, StreamingPlayer } from 'pocket-tts-js';

const Android=window.Android||{openDocument(){},getSystemVoices(){return'[]'},selectSystemVoice(){},speakSystem(){},stopSystem(){},openTtsSettings(){},appVersion(){return'dev'}};
const S={tab:'library',title:'',text:'',docId:'',segments:[],index:0,playing:false,mode:localStorage.voiceMode||'ai',language:localStorage.language||'auto',detected:'de',systemVoices:[],systemVoiceId:localStorage.systemVoiceId||'',rate:Number(localStorage.systemRate||'.92'),pitch:Number(localStorage.systemPitch||'.98'),paragraphPauses:localStorage.paragraphPauses!=='false',dialogueMode:localStorage.dialogueMode!=='false',rememberPosition:localStorage.rememberPosition!=='false',ai:{tts:null,player:null,language:null,ready:false,loading:false,progress:0,label:'',voices:[],builtInVoice:localStorage.aiVoice||'',activeVoice:null,useOwnVoice:localStorage.useOwnVoice==='true',ownReady:false,recordBlob:null,mediaRecorder:null,stream:null,started:0,token:0}};
const $=id=>document.getElementById(id);let recordTimer=null;

document.querySelector('#app').innerHTML=`<main class="shell"><header class="topbar"><div class="brand"><div class="logo">V</div><div><h1>VoxBook</h1><small>Dein persönlicher Hörbuch-Reader</small></div></div><div class="badge">v${Android.appVersion()}</div></header>
<section class="view active" data-view="library"><div class="hero"><h2>Aus Text wird eine Geschichte.</h2><p>Öffne ein PDF oder eine Textdatei und höre sie auf Deutsch oder Englisch – mit Systemstimme, KI-Erzähler oder deiner eigenen Stimme.</p><button class="primary wide" id="openDoc">＋ &nbsp; PDF oder Text öffnen</button></div><div class="card"><div class="card-title"><h3>Aktuelles Buch</h3><span id="docLang">Deutsch</span></div><div id="docEmpty" class="empty">Noch kein Dokument geöffnet.</div><div id="docInfo" class="hidden"><div class="doc-title" id="docTitle"></div><div class="meta" id="docMeta"></div><div class="progress"><div id="libProgress"></div></div><div class="progressline"><span id="libPosition">0 %</span><span id="libSegments">0 Abschnitte</span></div><div style="height:12px"></div><button class="secondary wide" id="continueBtn">Weiterhören</button></div></div><div class="card soft"><div class="card-title"><h3>Sprachfokus</h3><span>bewusst reduziert</span></div><div class="pills"><span class="pill active">🇩🇪 Deutsch</span><span class="pill active">🇬🇧 English</span></div><p class="meta">Andere Sprachen werden in VoxBook nicht angezeigt.</p></div></section>
<section class="view" data-view="player"><div class="card"><div class="card-title"><h3 id="playerTitle">Kein Buch geöffnet</h3><span id="playerMode">KI-Erzähler</span></div><div class="now" id="nowText">Öffne zuerst ein Dokument in der Bibliothek.</div><div class="progress"><div id="playerProgress"></div></div><div class="progressline"><span id="playerPos">0 / 0</span><span id="playerPercent">0 %</span></div><div class="transport"><button class="ghost" id="prevBtn">‹ Zurück</button><button class="primary" id="playBtn">▶ Vorlesen</button><button class="ghost" id="nextBtn">Weiter ›</button></div></div><div class="card soft"><div class="card-title"><h3>Vorleseart</h3><span id="engineState">bereit</span></div><div class="voice-grid"><button class="voice-option" id="modeAi"><strong>✦ KI-Erzähler</strong><small>Natürlich und flüssig wie ein Hörbuch.</small></button><button class="voice-option" id="modeSystem"><strong>◉ Systemstimme</strong><small>Sofort startklar mit Android-TTS.</small></button></div><div class="label">Sprache</div><div class="pills"><button class="pill" id="langDe">Deutsch</button><button class="pill" id="langEn">English</button><button class="pill" id="langAuto">Auto</button></div></div></section>
<section class="view" data-view="voices"><div class="card"><div class="card-title"><h3>KI-Erzähler</h3><span>Pocket-TTS · lokal</span></div><div class="status"><span class="dot" id="aiDot"></span><div id="aiStatus">Noch nicht geladen. Beim ersten Start werden nur die Dateien für Deutsch oder Englisch geladen.</div></div><div class="meter"><div id="aiMeter"></div></div><button class="primary wide" id="loadAi">KI-Stimmen laden</button><div class="label">Erzählerstimme</div><select class="select" id="aiVoiceSelect"><option>Modell zuerst laden</option></select><p class="tiny">Nach dem Download läuft die KI-Sprachausgabe auf deinem Gerät.</p></div><div class="card soft"><div class="card-title"><h3>Meine Stimme</h3><span>Voice Clone</span></div><p class="meta">Sprich etwa 8–12 Sekunden sauber und ohne Musik. VoxBook erstellt daraus lokal ein Stimmenprofil.</p><div class="status" id="recordStatus"><span class="dot"></span><div>Noch keine Aufnahme gespeichert.</div></div><div class="row" style="margin-top:13px"><button class="secondary grow" id="recordBtn">● Aufnahme starten</button><button class="ghost" id="deleteVoiceBtn">Löschen</button></div><div class="label">Empfohlener Sprechtext</div><div class="now" style="min-height:auto;max-height:none">„Heute lese ich eine Geschichte mit ruhiger Stimme. Ich spreche deutlich, natürlich und in meinem eigenen Tempo.“</div><div style="height:12px"></div><button class="primary wide" id="useOwnVoice">Eigene Stimme als Erzähler verwenden</button></div><div class="card"><div class="card-title"><h3>Android-Stimmen</h3><span>nur DE / EN</span></div><select class="select" id="systemVoiceSelect"><option>Stimmen werden geladen…</option></select><div style="height:10px"></div><button class="ghost wide" id="ttsSettings">Weitere Stimmen in Android verwalten</button></div></section>
<section class="view" data-view="settings"><div class="card"><div class="card-title"><h3>Hörbuch-Stil</h3><span>Erzählfluss</span></div><div class="toggle-row" id="pauseToggle"><div><strong>Sanfte Absatzpausen</strong><small>Absätze bekommen natürliche Atempausen.</small></div><span class="switch"></span></div><div class="toggle-row" id="dialogueToggle"><div><strong>Dialoge respektieren</strong><small>Satzzeichen bleiben für die Betonung erhalten.</small></div><span class="switch"></span></div><div class="toggle-row" id="rememberToggle"><div><strong>Position merken</strong><small>Beim nächsten Mal dort fortsetzen.</small></div><span class="switch"></span></div></div><div class="card soft"><div class="card-title"><h3>Systemstimme</h3><span>Fallback</span></div><div class="label">Tempo <span id="rateValue"></span></div><input class="range" id="rateRange" type="range" min="0.70" max="1.25" step="0.01"><div class="label">Tonhöhe <span id="pitchValue"></span></div><input class="range" id="pitchRange" type="range" min="0.80" max="1.20" step="0.01"></div><div class="card"><div class="card-title"><h3>KI-Modell</h3><span>lokal</span></div><p class="meta">Die KI-Modelle sind größer als die APK und werden nur geladen, wenn du sie benutzt.</p><button class="danger wide" id="clearAi">KI aus Arbeitsspeicher entfernen</button></div></section></main>
<nav class="nav"><button class="active" data-tab="library"><b>▤</b>Bibliothek</button><button data-tab="player"><b>▶</b>Player</button><button data-tab="voices"><b>◉</b>Stimmen</button><button data-tab="settings"><b>⚙</b>Einstellungen</button></nav><div class="toast" id="toast"></div>`;

function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2300)}
function tab(t){S.tab=t;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===t));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t))}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('openDoc').onclick=()=>Android.openDocument();$('continueBtn').onclick=()=>tab('player');$('ttsSettings').onclick=()=>Android.openTtsSettings();
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
function detect(t){const x=' '+t.slice(0,12000).toLowerCase()+' ';const de=[' der ',' die ',' das ',' und ',' ist ',' ich ',' nicht ',' ein ',' eine ',' mit ',' sich ',' auf ',' für ',' zu ',' dass ',' war ',' sie ',' er ',' im ',' den ',' dem ',' von ',' aber '];const en=[' the ',' and ',' is ',' i ',' not ',' a ',' an ',' with ',' to ',' that ',' was ',' she ',' he ',' in ',' of ',' but ',' as ',' for ',' you ',' it '];let d=0,e=0;de.forEach(w=>d+=x.split(w).length-1);en.forEach(w=>e+=x.split(w).length-1);if(/[äöüß]/i.test(x))d+=8;return e>d*1.12?'en':'de'}
function segments(text){const n=text.replace(/\r/g,'').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim();const out=[];for(const p0 of n.split(/\n\s*\n+/)){let p=p0.replace(/\s*\n\s*/g,' ').trim();if(!p)continue;const ss=p.match(/[^.!?…]+(?:[.!?…]+[”"“']?|$)/g)||[p];let b='';for(const r of ss){const q=r.trim();if(!q)continue;if(b&&b.length+q.length>520){out.push(b);b=''}b+=(b?' ':'')+q}if(b)out.push(b+(S.paragraphPauses?' …':''))}return out.length?out:[n]}
function lang(){return S.language==='auto'?S.detected:S.language}
function refresh(){const has=!!S.text;$('docEmpty').classList.toggle('hidden',has);$('docInfo').classList.toggle('hidden',!has);if(has){const p=S.segments.length?Math.round(S.index/S.segments.length*100):0;$('docTitle').textContent=S.title;$('docMeta').textContent=`${Math.round(S.text.length/1000)} Tsd. Zeichen · ${S.detected==='de'?'Deutsch':'English'} erkannt`;$('docLang').textContent=S.detected==='de'?'Deutsch':'English';$('libProgress').style.width=p+'%';$('libPosition').textContent=p+' %';$('libSegments').textContent=S.segments.length+' Abschnitte';$('playerTitle').textContent=S.title}refreshPlayer()}
function refreshPlayer(){const t=S.segments.length,p=t?Math.round((S.index+1)/t*100):0;$('playerProgress').style.width=(t?p:0)+'%';$('playerPos').textContent=t?`${Math.min(S.index+1,t)} / ${t}`:'0 / 0';$('playerPercent').textContent=(t?p:0)+' %';$('nowText').textContent=t?S.segments[Math.min(S.index,t-1)]:'Öffne zuerst ein Dokument in der Bibliothek.';$('playBtn').textContent=S.playing?'⏸ Pause':'▶ Vorlesen';$('playerMode').textContent=S.mode==='ai'?(S.ai.useOwnVoice?'Meine Stimme':'KI-Erzähler'):'Systemstimme';$('modeAi').classList.toggle('active',S.mode==='ai');$('modeSystem').classList.toggle('active',S.mode==='system');$('langDe').classList.toggle('active',S.language==='de');$('langEn').classList.toggle('active',S.language==='en');$('langAuto').classList.toggle('active',S.language==='auto');if(S.rememberPosition&&S.docId)localStorage.setItem('pos:'+S.docId,String(S.index))}
function stop(){S.playing=false;S.ai.token++;try{S.ai.tts?.stop?.();S.ai.player?.stop?.();Android.stopSystem()}catch{}refreshPlayer()}
function jump(d){if(!S.segments.length)return;const was=S.playing;stop();S.index=Math.max(0,Math.min(S.segments.length-1,S.index+d));refreshPlayer();if(was)start()}
$('prevBtn').onclick=()=>jump(-1);$('nextBtn').onclick=()=>jump(1);$('playBtn').onclick=()=>S.playing?stop():start();
$('modeAi').onclick=()=>{stop();S.mode='ai';localStorage.voiceMode='ai';refreshPlayer()};$('modeSystem').onclick=()=>{stop();S.mode='system';localStorage.voiceMode='system';refreshPlayer()};
function setLang(v){stop();S.language=v;localStorage.language=v;refreshPlayer();systemVoices();if(S.ai.ready&&S.ai.language!==lang())unloadAi()}$('langDe').onclick=()=>setLang('de');$('langEn').onclick=()=>setLang('en');$('langAuto').onclick=()=>setLang('auto');
async function start(){if(!S.segments.length){toast('Öffne zuerst ein Dokument.');tab('library');return}if(S.index>=S.segments.length)S.index=0;S.playing=true;refreshPlayer();if(S.mode==='ai')await aiNarrate();else systemNarrate()}
function systemNarrate(){if(!S.playing||S.index>=S.segments.length){finish();return}$('engineState').textContent='Systemstimme';Android.speakSystem(S.segments[S.index],lang(),S.rate,S.pitch)}
function finish(){S.playing=false;S.index=Math.max(0,S.segments.length-1);refreshPlayer();toast('Ende des Dokuments.')}
window.VoxNative={loadingDocument(){toast('Dokument wird eingelesen …')},documentReady(title,text){stop();S.title=title||'Dokument';S.text=text||'';S.detected=detect(S.text);S.docId=hash(S.title+'|'+S.text.length+'|'+S.text.slice(0,200));S.segments=segments(S.text);S.index=S.rememberPosition?Number(localStorage.getItem('pos:'+S.docId)||0):0;if(S.index>=S.segments.length)S.index=0;refresh();toast('Dokument ist bereit.');tab('library')},documentError(m){toast('PDF konnte nicht gelesen werden: '+(m||'Fehler'))},systemDone(){if(!S.playing||S.mode!=='system')return;S.index++;refreshPlayer();if(S.index<S.segments.length)setTimeout(systemNarrate,S.paragraphPauses?180:30);else finish()},systemError(){S.playing=false;refreshPlayer();toast('Systemstimme konnte nicht vorlesen.')}};

async function ensureAi(){const l=lang();if(S.ai.ready&&S.ai.language===l)return true;if(S.ai.loading)return false;S.ai.loading=true;S.ai.progress=0;uiAi();try{S.ai.tts=new PocketTTS({language:l==='de'?'german':'english',quantized:true,voiceCloning:true,maxThreads:4});await S.ai.tts.load(p=>{if(p?.total){S.ai.progress=Math.round(p.loaded/p.total*100);S.ai.label=p.label||'Modell';uiAi()}});S.ai.player=new StreamingPlayer({sampleRate:S.ai.tts.sampleRate});await S.ai.player.resume();S.ai.language=l;S.ai.ready=true;S.ai.loading=false;S.ai.progress=100;S.ai.voices=Array.from(S.ai.tts.predefinedVoices||[]);fillAiVoices();if(S.ai.useOwnVoice)await ownVoice();else await builtVoice();uiAi();return true}catch(e){console.error(e);S.ai.loading=false;S.ai.ready=false;S.ai.label='Fehler: '+(e?.message||e);uiAi();toast('KI-Modell konnte nicht geladen werden.');return false}}
function unloadAi(){try{S.ai.tts?.stop?.();S.ai.tts?.destroy?.();S.ai.player?.stop?.()}catch{}Object.assign(S.ai,{tts:null,player:null,language:null,ready:false,loading:false,progress:0,label:'',activeVoice:null,ownReady:false});uiAi()}
async function builtVoice(){if(!S.ai.ready)return;let v=S.ai.builtInVoice;if(!v||!S.ai.voices.includes(v))v=S.ai.voices[0]||(lang()==='de'?'juergen':'alba');try{S.ai.activeVoice=await S.ai.tts.loadVoice(v);S.ai.builtInVoice=v;localStorage.aiVoice=v}catch(e){console.warn(e);S.ai.activeVoice=null}}
async function aiNarrate(){const tok=++S.ai.token;const ok=await ensureAi();if(!ok||!S.playing||tok!==S.ai.token){S.playing=false;refreshPlayer();return}if(S.ai.useOwnVoice&&!S.ai.activeVoice){if(!await ownVoice()){S.playing=false;refreshPlayer();tab('voices');return}}if(!S.ai.useOwnVoice&&!S.ai.activeVoice)await builtVoice();if(!S.ai.activeVoice){toast('Keine KI-Stimme verfügbar.');S.playing=false;refreshPlayer();return}$('engineState').textContent=S.ai.useOwnVoice?'Meine Stimme':'KI-Erzähler';while(S.playing&&tok===S.ai.token&&S.index<S.segments.length){refreshPlayer();try{await S.ai.tts.generate(S.segments[S.index],{voice:S.ai.activeVoice,onChunk:(audio,meta)=>S.ai.player.play(audio,meta)})}catch(e){console.error(e);S.playing=false;refreshPlayer();toast('KI-Vorlesen wurde unterbrochen.');return}if(!S.playing||tok!==S.ai.token)return;S.index++;refreshPlayer()}try{S.ai.player?.flush?.()}catch{}if(S.index>=S.segments.length)finish()}
function uiAi(){$('aiMeter').style.width=(S.ai.progress||0)+'%';$('aiDot').className='dot '+(S.ai.ready?'ok':S.ai.loading?'work':'');$('aiStatus').textContent=S.ai.ready?`Bereit · ${S.ai.language==='de'?'Deutsch':'English'} · ${S.ai.voices.length||'mehrere'} Stimmen`:S.ai.loading?`${S.ai.label||'Lädt'} · ${S.ai.progress}%`:S.ai.label||'Noch nicht geladen. Beim ersten Start wird nur Deutsch oder Englisch geladen.';$('loadAi').textContent=S.ai.ready?'KI-Stimmen sind bereit':S.ai.loading?'Wird geladen …':'KI-Stimmen laden';$('loadAi').disabled=S.ai.loading;$('engineState').textContent=S.mode==='ai'?(S.ai.ready?'KI bereit':S.ai.loading?`KI lädt ${S.ai.progress}%`:'KI noch nicht geladen'):'System bereit'}
$('loadAi').onclick=()=>ensureAi();function fillAiVoices(){const e=$('aiVoiceSelect');e.innerHTML='';if(!S.ai.voices.length){e.innerHTML='<option>Standard-Erzähler</option>';return}S.ai.voices.forEach((v,i)=>{const o=document.createElement('option');o.value=v;o.textContent=`Erzähler ${i+1} · ${String(v).replace(/[_-]/g,' ')}`;o.selected=v===S.ai.builtInVoice;e.appendChild(o)})}$('aiVoiceSelect').onchange=async()=>{S.ai.useOwnVoice=false;localStorage.useOwnVoice='false';S.ai.builtInVoice=$('aiVoiceSelect').value;localStorage.aiVoice=S.ai.builtInVoice;if(S.ai.ready)await builtVoice();ownUi();refreshPlayer()};
function systemVoices(){try{S.systemVoices=JSON.parse(Android.getSystemVoices()||'[]')}catch{S.systemVoices=[]}const list=S.systemVoices.filter(v=>v.lang===lang()),e=$('systemVoiceSelect');e.innerHTML='';if(!list.length){e.innerHTML='<option>Keine passende Stimme gefunden</option>';return}list.forEach(v=>{const o=document.createElement('option');o.value=v.id;o.textContent=v.name+(v.online?' · online':' · offline');o.selected=v.id===S.systemVoiceId;e.appendChild(o)});if(!S.systemVoiceId){S.systemVoiceId=list[0].id;Android.selectSystemVoice(S.systemVoiceId)}}setTimeout(systemVoices,700);$('systemVoiceSelect').onchange=()=>{S.systemVoiceId=$('systemVoiceSelect').value;localStorage.systemVoiceId=S.systemVoiceId;Android.selectSystemVoice(S.systemVoiceId)};

const DB='voxbook-voice',STORE='samples';function odb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}async function put(k,v){const d=await odb();return new Promise((ok,no)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(v,k);t.oncomplete=ok;t.onerror=()=>no(t.error)})}async function get(k){const d=await odb();return new Promise((ok,no)=>{const r=d.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}async function del(k){const d=await odb();return new Promise((ok,no)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).delete(k);t.oncomplete=ok;t.onerror=()=>no(t.error)})}
async function record(){try{const st=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}}),parts=[],r=new MediaRecorder(st);S.ai.mediaRecorder=r;S.ai.stream=st;S.ai.started=Date.now();r.ondataavailable=e=>e.data?.size&&parts.push(e.data);r.onstop=async()=>{st.getTracks().forEach(t=>t.stop());S.ai.stream=null;S.ai.mediaRecorder=null;const b=new Blob(parts,{type:r.mimeType||'audio/webm'});S.ai.recordBlob=b;await put('voice',b);S.ai.ownReady=false;ownUi();toast('Aufnahme gespeichert.');if(S.ai.ready)await ownVoice()};r.start(250);ownUi();recordTimer=setInterval(()=>{ownUi();if(Date.now()-S.ai.started>12000&&r.state==='recording')stopRecord()},250)}catch(e){console.error(e);toast('Mikrofon konnte nicht geöffnet werden.')}}function stopRecord(){clearInterval(recordTimer);recordTimer=null;const r=S.ai.mediaRecorder;if(r?.state==='recording')r.stop()}$('recordBtn').onclick=()=>S.ai.mediaRecorder?.state==='recording'?stopRecord():record();
async function mono(blob){const b=await blob.arrayBuffer(),c=new AudioContext(),a=await c.decodeAudioData(b.slice(0));let x=a.getChannelData(0);if(a.numberOfChannels>1){const m=new Float32Array(a.length);for(let ch=0;ch<a.numberOfChannels;ch++){const q=a.getChannelData(ch);for(let i=0;i<m.length;i++)m[i]+=q[i]/a.numberOfChannels}x=m}const o={data:new Float32Array(x),sampleRate:a.sampleRate};await c.close();return o}
async function ownVoice(){if(!S.ai.ready){toast('Lade zuerst die KI-Stimmen.');return false}let b=S.ai.recordBlob||await get('voice').catch(()=>null);if(!b){toast('Nimm zuerst deine Stimme auf.');return false}try{const a=await mono(b);$('recordStatus').innerHTML='<span class="dot work"></span><div>Stimmenprofil wird erstellt …</div>';S.ai.activeVoice=await S.ai.tts.cloneVoice(a.data,{inputSampleRate:a.sampleRate,name:'voxbook-me'});S.ai.ownReady=true;S.ai.useOwnVoice=true;localStorage.useOwnVoice='true';await ownUi();refreshPlayer();toast('Deine Stimme ist einsatzbereit.');return true}catch(e){console.error(e);S.ai.ownReady=false;await ownUi();toast('Stimmenprofil konnte nicht erstellt werden.');return false}}
async function ownUi(){const rec=S.ai.mediaRecorder?.state==='recording',saved=!!S.ai.recordBlob||!!await get('voice').catch(()=>null);if(rec){const s=Math.min(12,(Date.now()-S.ai.started)/1000).toFixed(1);$('recordStatus').innerHTML=`<span class="dot work"></span><div>Aufnahme läuft · ${s} / 12 s</div>`;$('recordBtn').textContent='■ Aufnahme beenden'}else if(S.ai.ownReady){$('recordStatus').innerHTML='<span class="dot ok"></span><div>Stimmenprofil ist erstellt und bereit.</div>';$('recordBtn').textContent='● Neu aufnehmen'}else if(saved){$('recordStatus').innerHTML='<span class="dot ok"></span><div>Aufnahme gespeichert · bereit zum Klonen.</div>';$('recordBtn').textContent='● Neu aufnehmen'}else{$('recordStatus').innerHTML='<span class="dot"></span><div>Noch keine Aufnahme gespeichert.</div>';$('recordBtn').textContent='● Aufnahme starten'}$('useOwnVoice').textContent=S.ai.useOwnVoice?'✓ Eigene Stimme ist ausgewählt':'Eigene Stimme als Erzähler verwenden'}$('useOwnVoice').onclick=async()=>{if(!S.ai.ready&&!(await ensureAi()))return;if(await ownVoice())tab('player')};$('deleteVoiceBtn').onclick=async()=>{stop();await del('voice');S.ai.recordBlob=null;S.ai.ownReady=false;S.ai.useOwnVoice=false;S.ai.activeVoice=null;localStorage.useOwnVoice='false';if(S.ai.ready)await builtVoice();await ownUi();refreshPlayer();toast('Eigene Stimme gelöscht.')};
function togg(k){S[k]=!S[k];localStorage[k]=String(S[k]);if(k!=='rememberPosition'){const r=S.segments.length?S.index/S.segments.length:0;S.segments=segments(S.text||'');S.index=Math.max(0,Math.min(S.segments.length-1,Math.floor(r*S.segments.length)))}settings();refreshPlayer()}$('pauseToggle').onclick=()=>togg('paragraphPauses');$('dialogueToggle').onclick=()=>togg('dialogueMode');$('rememberToggle').onclick=()=>togg('rememberPosition');function settings(){$('pauseToggle').querySelector('.switch').classList.toggle('on',S.paragraphPauses);$('dialogueToggle').querySelector('.switch').classList.toggle('on',S.dialogueMode);$('rememberToggle').querySelector('.switch').classList.toggle('on',S.rememberPosition);$('rateRange').value=S.rate;$('pitchRange').value=S.pitch;$('rateValue').textContent=S.rate.toFixed(2)+'×';$('pitchValue').textContent=S.pitch.toFixed(2)}$('rateRange').oninput=()=>{S.rate=Number($('rateRange').value);localStorage.systemRate=S.rate;settings()};$('pitchRange').oninput=()=>{S.pitch=Number($('pitchRange').value);localStorage.systemPitch=S.pitch;settings()};$('clearAi').onclick=()=>{stop();unloadAi();toast('KI aus dem Arbeitsspeicher entfernt.')};
settings();refreshPlayer();uiAi();ownUi();
